// Auto-generated by figma-image skill
export const cdnHost = '//glep-img.golingo.cn'
export const cdnUrlPrefix = `${cdnHost}/glep-web-lang-edu/lang-edu/images`
export const constImg = {
  // Add your image keys here
  // example: my_image: `${cdnUrlPrefix}/my-image.png`,
}
