"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.STORAGE_LOGIN_KEY = exports.ERROR_STATUS_CODE_UNAUTHORIZED = exports.ERROR_STATUS_CODE_SERVER = exports.ERROR_STATUS_CODE_NOT_FOUND = exports.ERROR_STATUS_CODE_METHOD_NOT_ALLOWED = exports.ERROR_STATUS_CODE_FORBIDDEN = exports.CODE_NO_LOGIN = exports.CODE_LOGIN_INVALID = void 0;
var STORAGE_LOGIN_KEY = exports.STORAGE_LOGIN_KEY = 'STORAGE_LOGIN_KEY';
var CODE_NO_LOGIN = exports.CODE_NO_LOGIN = 'CODE_NO_LOGIN';
var CODE_LOGIN_INVALID = exports.CODE_LOGIN_INVALID = 'CODE_LOGIN_INVALID';
var ERROR_STATUS_CODE_SERVER = exports.ERROR_STATUS_CODE_SERVER = 500;

// 未登录
var ERROR_STATUS_CODE_UNAUTHORIZED = exports.ERROR_STATUS_CODE_UNAUTHORIZED = 401;

// 无权限
var ERROR_STATUS_CODE_FORBIDDEN = exports.ERROR_STATUS_CODE_FORBIDDEN = 403;

// 结构不存在
var ERROR_STATUS_CODE_NOT_FOUND = exports.ERROR_STATUS_CODE_NOT_FOUND = 404;

//  请求方法不支持、header参数不支持
var ERROR_STATUS_CODE_METHOD_NOT_ALLOWED = exports.ERROR_STATUS_CODE_METHOD_NOT_ALLOWED = 405;