const https = require('https')
const fs = require('fs')
const path = require('path')
const os = require('os')

const FIGMA_TOKEN = process.env.FIGMA_TOKEN || ''
const TEMP_DIR = path.join(os.tmpdir(), 'figma-images')

// 确保临时目录存在
if (!fs.existsSync(TEMP_DIR)) {
  fs.mkdirSync(TEMP_DIR, { recursive: true })
}

/**
 * 从 Figma 链接提取文件 ID 和节点 ID
 * 链接格式: https://www.figma.com/design/FILE_ID?node-id=NODE_ID
 */
function parseFigmaUrl(url) {
  const designMatch = url.match(/figma\.com\/design\/([a-zA-Z0-9]+)/)
  if (!designMatch) {
    throw new Error('Invalid Figma URL. Expected format: https://www.figma.com/design/FILE_ID?node-id=NODE_ID')
  }

  const fileKey = designMatch[1]
  let nodeId = null

  const nodeIdMatch = url.match(/node-id=([^&]+)/)
  if (nodeIdMatch) {
    nodeId = decodeURIComponent(nodeIdMatch[1])
  }

  return { fileKey, nodeId }
}

/**
 * 调用 Figma API 获取图片
 */
function fetchFigmaImage(fileKey, nodeId, imageName) {
  return new Promise((resolve, reject) => {
    if (!FIGMA_TOKEN) {
      reject(new Error('FIGMA_TOKEN environment variable is required'))
      return
    }

    // 构建 API 请求
    const ids = nodeId
    const apiUrl = `https://api.figma.com/v1/images/${fileKey}?ids=${encodeURIComponent(ids)}&format=png&scale=2`

    const options = {
      headers: {
        'X-Figma-Token': FIGMA_TOKEN,
      },
    }

    https.get(apiUrl, options, (res) => {
      let data = ''
      res.on('data', (chunk) => (data += chunk))
      res.on('end', () => {
        try {
          const result = JSON.parse(data)
          if (result.err) {
            reject(new Error(result.err))
            return
          }

          const imageUrl = result.images?.[nodeId]
          if (!imageUrl) {
            reject(new Error('Failed to get image URL from Figma API'))
            return
          }

          resolve(imageUrl)
        } catch (e) {
          reject(e)
        }
      })
    }).on('error', reject)
  })
}

/**
 * 下载图片到临时目录
 */
function downloadImage(imageUrl, imageName) {
  return new Promise((resolve, reject) => {
    const fileName = `${imageName || 'image'}-${Date.now()}.png`
    const filePath = path.join(TEMP_DIR, fileName)

    const file = fs.createWriteStream(filePath)
    https.get(imageUrl, (response) => {
      response.pipe(file)
      file.on('finish', () => {
        file.close()
        resolve(filePath)
      })
    }).on('error', (err) => {
      fs.unlink(filePath, () => {})
      reject(err)
    })
  })
}

/**
 * 读取 const-img.ts 文件
 */
function readConstImgFile() {
  const filePath = path.resolve(__dirname, '../../cli/src/contants/const-img.ts')
  if (fs.existsSync(filePath)) {
    return fs.readFileSync(filePath, 'utf-8')
  }
  return null
}

/**
 * 写入 const-img.ts 文件
 */
function writeConstImgFile(content, constKey, url) {
  const filePath = path.resolve(__dirname, '../../cli/src/contants/const-img.ts')
  const dir = path.dirname(filePath)

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  // 解析现有内容，添加新图片
  let constImg = {}

  if (content) {
    // 尝试提取现有的 constImg 对象
    const match = content.match(/export\s+const\s+constImg\s*=\s*\{([^}]*)\}/s)
    if (match) {
      // 简单解析现有对象
      const entries = match[1].matchAll(/(\w+):\s*`([^`]+)`/g)
      for (const entry of entries) {
        constImg[entry[1]] = entry[2]
      }
    }
  }

  // 添加新图片
  constImg[constKey] = url

  // 构建文件内容
  const cdnHost = '//glep-img.golingo.cn'
  const cdnUrlPrefix = `${cdnHost}/glep-web-lang-edu/lang-edu/images`

  let constImgStr = '{\n'
  for (const [key, value] of Object.entries(constImg)) {
    constImgStr += `  ${key}: \`${value}\`,\n`
  }
  constImgStr += '}'

  const fileContent = `// Auto-generated by figma-image skill
export const cdnHost = '${cdnHost}'
export const cdnUrlPrefix = \`\${cdnHost}/glep-web-lang-edu/lang-edu/images\`
export const constImg = ${constImgStr}
`

  fs.writeFileSync(filePath, fileContent, 'utf-8')
  return filePath
}

exports.handler = async ({ figma_url, image_name }) => {
  // 验证输入
  if (!figma_url) {
    throw new Error('figma_url is required')
  }

  if (!image_name) {
    throw new Error('image_name is required')
  }

  // 解析 Figma URL
  const { fileKey, nodeId } = parseFigmaUrl(figma_url)

  if (!nodeId) {
    throw new Error('node-id is required in Figma URL')
  }

  console.log(`Fetching image from Figma file: ${fileKey}, node: ${nodeId}`)

  // 获取图片 URL
  const imageUrl = await fetchFigmaImage(fileKey, nodeId, image_name)
  console.log(`Downloading image from: ${imageUrl}`)

  // 下载到临时目录
  const localPath = await downloadImage(imageUrl, image_name)
  console.log(`Image downloaded to: ${localPath}`)

  // 返回本地路径，供 upload_to_obs skill 使用
  // 注意: 实际的 OBS 上传和 const-img.ts 更新需要通过其他 skill 或手动完成
  return {
    localPath,
    fileKey,
    nodeId,
    message: `Image downloaded to ${localPath}. Use upload_to_obs skill to upload and register to const-img.ts`,
  }
}
